name: Pipeline
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Copy the files from the repo
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.1'

      - name: Install poetry
        run: pip install poetry

      - name: Install project dependencies
        run: poetry install --without docs

      - name: Run the tests
        run: poetry run task test --cov-report=xml

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}